### ISSUE TITLE
Where can I get the testscene.josn and island.json

### ISSUE THREAD

**Issue by lyd405121** [schuttejoe/Selas#2]
I am writing a gpu based Bsdf path tracer.
Your article is really helpful, since I have never seen any BSDF code  wriiten by other people.
When I download your code, the json file is missing.
So where can I get the testscene.josn and island.json(I download disney asset, nearly 200GB, not found yet), or should I write one json file by myself?

**Comment by schuttejoe** [comment]
The testscene.json and island.json files were hand authored by me. I'd
recommend against trying to run my code and just use it as a reference
instead.

**Comment by lyd405121** [comment]
Get it. I will write my own cuda code  and just use it as a reference. Thanks!
